OBJS+=		glue.o
R=		../../..
K=		$R/kernel
CFLAGS=		-std=c99 -I$R/include -I. -DKERNEL -DMODULE
LDFLAGS=	-r
ARCH?=		i386

$(TARGET).ko:	$(OBJS) $K/modules/common/ldscript.module
		$(LD) -T $K/modules/common/ldscript.module -o $(TARGET).ko $(OBJS) $(LDFLAGS)

clean:
		rm -f $(TARGET).ko machine $(OBJS)

glue.o:		machine $K/modules/common/glue.c
		$(CC) -c -o glue.o $K/modules/common/glue.c $(CFLAGS)

machine:
		ln -sf $R/include/ananas/${ARCH} machine
