TARGET:		kernel

S=		../../../..

%OBJS
%FILES

CFLAGS=		-m32 -march=i386 -I$S/../include -I$S -I. -std=c99
kernel:		$(OBJS) $S/conf/ld.i386
		$(LD) -b elf32-i386 -T $S/conf/ld.i386 -o kernel $(OBJS)

kernel.symbols:	kernel
		nm kernel|awk '{print $$1" "$$3}'|sort > kernel.symbols

clean:
		rm -f kernel $(OBJS)
