# general cflags
CFLAGS+=		-g
# cflags for our wrapper code
WCFLAGS+=	-std=c99 -I. -I../framework/include $(CFLAGS)
# cflags for kernel stuff
KCFLAGS+=	$(WCFLAGS) -I../../include $(CFLAGS) -DTESTFRAMEWORK

ARCH?=		amd64
K?=		../../kernel

$(TARGET):	$(OBJS) $(LIBS) ld.script
		$(CC) -o $(TARGET) -T ld.script $(OBJS) $(LIBS)

machine:
		ln -sf ../../include/ananas/${ARCH} machine

ananas:		machine
		ln -sf ../../include/ananas

test:		$(TARGET)
		./$(TARGET)

ld.script:
		$(LD) --verbose|../framework/make-ldscript.pl > ld.script

clean:
		rm -f $(TARGET) machine ananas options.h ld.script $(OBJS) $(CLEAN_FILES)
