#include "console.h"
#include "device.h"
#include "lib.h"
#include "mm.h"
#include "console.inc"

/*
 * devprobe.inc will be generated by config and just lists all drivers we have
 * to probe.
 */
#include "devprobe.inc"

/*
 * devhints.inc will be generated by config and lists all hints we have.
 */
#include "hints.inc"

static device_t corebus = NULL;

device_t
device_alloc(device_t bus, driver_t drv)
{
	KASSERT(drv != NULL, "tried to allocate a NULL driver");

	device_t dev = kmalloc(sizeof(device_t));
	memset(dev, 0, sizeof(device_t));
	dev->driver = drv;
	dev->parent = bus;
	dev->unit = 0; /* XXX */
	strcpy(dev->name, drv->name);
	return dev;
}

int
device_attach_single(device_t dev)
{
	int result;
	driver_t driver = dev->driver;

	if (driver->drv_probe != NULL) {
		/*
		 * This device has a probe function; we must call it to figure out
	 	 * whether the device actually exists or we're about to attach
		 * something out of thin air here...
		 */
		result = driver->drv_probe(dev);
		if (result)
			return result;
	}
	if (driver->drv_attach != NULL) {
		result = driver->drv_attach(dev);
		if (result)
			return result;
	}

	return 0;
}

static int
device_resolve_type(char** value)
{
	if (!memcmp(*value, "mem=", 4)) {
		*value += 4;
		return RESTYPE_MEMORY;
	}
	if (!memcmp(*value, "io=", 3)) {
		*value += 3;
		return RESTYPE_IO;
	}
	if (!memcmp(*value, "irq=", 4)) {
		*value += 4;
		return RESTYPE_IRQ;
	}
	return RESTYPE_UNUSED;
}

/*
 * Handles retrieving the resources for a bus.device.unit from
 * the hints.
 */
int
device_get_resources(device_t dev, const char** hints)
{
	const char** curhint;
	char tmpname[32 /* XXX */];

	memset(dev->resource, 0, sizeof(struct RESOURCE) * DEVICE_MAX_RESOURCES);

	if (dev->parent != NULL)
		sprintf(tmpname, "%s.%s.%u.", dev->parent->name, dev->name, dev->unit);
	else
		sprintf(tmpname, "%s.%u.", dev->name, dev->unit);

	unsigned int numhints = 0;
	for (curhint = hints; *curhint != NULL; curhint++) {
		if (strlen(*curhint) < strlen(tmpname))
			continue;
		if (memcmp(*curhint, tmpname, strlen(tmpname)))
			continue;

		/*
		 * We got a resource match; need to figure out the type.
		 */
		char* value = (char*)(*curhint + strlen(tmpname));
		int type = device_resolve_type(&value);
		if (type == RESTYPE_UNUSED) {
			kprintf("%s: ignoring unparsable resource '%s'\n", dev->name, *curhint);
			continue;
		}
		unsigned long v = strtoul(value, NULL, 0);
		if (numhints >= DEVICE_MAX_RESOURCES) {
			kprintf("%s: skipping resource type 0x%x, too many specified\n", dev->name, type);
			continue;
		}
		dev->resource[numhints].type = type;
		dev->resource[numhints].base = v;
		numhints++;
	}
}

static void
device_print_attachment(device_t dev)
{
	KASSERT(dev->parent != NULL, "can't print device which doesn't have a parent bus");
	kprintf("%s%u on %s%u ", dev->name, dev->unit, dev->parent->name, dev->parent->unit);
	int i;
	for (i = 0; i < DEVICE_MAX_RESOURCES; i++) {
		switch (dev->resource[i].type) {
			case RESTYPE_MEMORY: kprintf("memory "); break;
			case RESTYPE_IO: kprintf("io "); break;
			case RESTYPE_IRQ: kprintf("irq "); break;
			default: continue;
		}
		kprintf("0x%x", dev->resource[i].base);
		if (dev->resource[i].length > 0)
			kprintf("-0x%x", dev->resource[i].base + dev->resource[i].length);
		kprintf(" ");
	}
	kprintf("\n");
}

/*
 * Handles attaching devices to a bus; may recursively call itself.
 */
void
device_attach_bus(device_t bus)
{
	for (struct PROBE** p = devprobe; *p != NULL; p++) {
		/* See if the device exists on this bus */
		int exists = 0;
		for (const char** curbus = (*p)->bus; *curbus != NULL; curbus++) {
			if (strcmp(*curbus, bus->name) == 0) {
				exists = 1;
				break;
			}
		}

		if (!exists)
			continue;

		/*
		 * OK, the device may be present on this bus; allocate a device for it.
		 */
		driver_t driver = (*p)->driver;
		KASSERT(driver != NULL, "matched a probe device without a driver!");

		/*
		 * If a console driver was specified, we need to skip attaching it
		 * again; we cheat and claim we attached it, yet we already did a long
		 * time ago ;-)
		 * 
		 */
#ifdef CONSOLE_DRIVER
		extern struct DRIVER CONSOLE_DRIVER;
		if (driver == &CONSOLE_DRIVER) {
			console_dev->parent = bus;
			device_print_attachment(console_dev);
			continue;
		}
#endif

		device_t dev = device_alloc(bus, driver);
		device_get_resources(dev, config_hints);
		int result = device_attach_single(dev);
		if (result != 0) {
			kfree(dev);
			continue;
		}

		/* We have a device; tell the user and see if anything lives on this bus */
		device_print_attachment(dev);
		device_attach_bus(dev);
	}
}

void
device_init()
{
	/*
	 * First of all, create the core bus; this is as bare to the metal as it
	 * gets.
	 */
	corebus = (device_t)kmalloc(sizeof(device_t));
	memset(corebus, 0, sizeof(device_t));
	strcpy(corebus->name, "corebus");
	device_attach_bus(corebus);
}

/* vim:set ts=2 sw=2: */
