TARGET:		libc.a

CFLAGS=		-m32 -march=i386 -I$S/../include -std=c99

MDOBJS		+= syscall.o

include Makefile.std

syscall.o:	$S/arch/i386/syscall.S
		$(CC) $(ASMFLAGS) -c -o syscall.o $S/arch/i386/syscall.S

